### ISSUE TITLE
Can we get an autogenerated README.md in the skeleton project

### ISSUE THREAD

**Issue by mwtsn** [kapow-wp/kapow-skeleton#5]
Anyway to auto generate a README.md with basic instructions, such as how to get up and running with VVV etc?

**Comment by davetgreen** [comment]
@mwtsn I'm about half way into some research for stuff like that. Should have it sorted next week or two.

**Comment by davetgreen** [comment]
@mwtsn will definitely be picking this up, maybe this week but definitely next week. 👌

**Comment by davetgreen** [comment]
Closing off in favour of a project documentation approach once we've updated the workflow.
